import '../../models/cost_estimate.dart';
import '../../models/travel_place.dart';

/// Offline sample data, used only when no Google API key is configured.
/// Amounts are explicit USD so the mock plan has a coherent currency.
const mockTokyoPlaces = <TravelPlace>[
  TravelPlace(
    id: 'shibuya_sky',
    name: 'Shibuya Sky',
    category: 'attractions',
    tags: ['photography', 'attractions', 'city view'],
    rating: 4.6,
    reviewCount: 18000,
    cost: CostEstimate(
      low: 25,
      high: 25,
      currencyCode: 'USD',
      source: CostSource.userProvided,
    ),
    latitude: 35.6584,
    longitude: 139.7022,
    estimatedVisitMinutes: 90,
  ),
  TravelPlace(
    id: 'sensoji',
    name: 'Senso-ji',
    category: 'history',
    tags: ['history', 'culture', 'photography'],
    rating: 4.5,
    reviewCount: 76000,
    cost: CostEstimate.free(currencyCode: 'USD'),
    latitude: 35.7148,
    longitude: 139.7967,
    estimatedVisitMinutes: 90,
  ),
  TravelPlace(
    id: 'meiji_shrine',
    name: 'Meiji Shrine',
    category: 'culture',
    tags: ['history', 'culture', 'nature'],
    rating: 4.6,
    reviewCount: 39000,
    cost: CostEstimate.free(currencyCode: 'USD'),
    latitude: 35.6764,
    longitude: 139.6993,
    estimatedVisitMinutes: 90,
  ),
  TravelPlace(
    id: 'teamlab',
    name: 'teamLab Borderless',
    category: 'attractions',
    tags: ['photography', 'culture', 'attractions'],
    rating: 4.6,
    reviewCount: 21000,
    cost: CostEstimate(
      low: 35,
      high: 35,
      currencyCode: 'USD',
      source: CostSource.userProvided,
    ),
    latitude: 35.6605,
    longitude: 139.7292,
    estimatedVisitMinutes: 120,
  ),
  TravelPlace(
    id: 'tsukiji',
    name: 'Tsukiji Outer Market',
    category: 'food',
    tags: ['food', 'local food', 'culture'],
    rating: 4.3,
    reviewCount: 57000,
    cost: CostEstimate(
      low: 30,
      high: 30,
      currencyCode: 'USD',
      source: CostSource.userProvided,
    ),
    latitude: 35.6655,
    longitude: 139.7707,
    estimatedVisitMinutes: 120,
  ),
  TravelPlace(
    id: 'ueno_museum',
    name: 'Tokyo National Museum',
    category: 'museums',
    tags: ['museums', 'history', 'culture'],
    rating: 4.5,
    reviewCount: 25000,
    cost: CostEstimate(
      low: 8,
      high: 8,
      currencyCode: 'USD',
      source: CostSource.userProvided,
    ),
    latitude: 35.7188,
    longitude: 139.7765,
    estimatedVisitMinutes: 150,
  ),
  TravelPlace(
    id: 'imperial_palace',
    name: 'Imperial Palace East Gardens',
    category: 'history',
    tags: ['history', 'nature', 'photography'],
    rating: 4.4,
    reviewCount: 12000,
    cost: CostEstimate.free(currencyCode: 'USD'),
    latitude: 35.6852,
    longitude: 139.7528,
    estimatedVisitMinutes: 100,
  ),
  TravelPlace(
    id: 'divercity_tokyo_plaza',
    name: 'DiverCity Tokyo Plaza',
    category: 'shopping_mall',
    tags: ['shopping', 'shopping_mall', 'attractions'],
    rating: 4.4,
    reviewCount: 38000,
    cost: CostEstimate(
      low: 20,
      high: 20,
      currencyCode: 'USD',
      source: CostSource.userProvided,
    ),
    latitude: 35.6252,
    longitude: 139.7756,
    estimatedVisitMinutes: 120,
  ),
  TravelPlace(
    id: 'tokyo_tower',
    name: 'Tokyo Tower',
    category: 'attractions',
    tags: ['photography', 'attractions', 'city view'],
    rating: 4.5,
    reviewCount: 74000,
    cost: CostEstimate(
      low: 22,
      high: 22,
      currencyCode: 'USD',
      source: CostSource.userProvided,
    ),
    latitude: 35.6586,
    longitude: 139.7454,
    estimatedVisitMinutes: 90,
  ),
  TravelPlace(
    id: 'yanaka',
    name: 'Yanaka Ginza',
    category: 'food',
    tags: ['local food', 'shopping', 'culture'],
    rating: 4.2,
    reviewCount: 9000,
    cost: CostEstimate(
      low: 18,
      high: 18,
      currencyCode: 'USD',
      source: CostSource.userProvided,
    ),
    latitude: 35.7276,
    longitude: 139.7655,
    estimatedVisitMinutes: 100,
  ),
  TravelPlace(
    id: 'mori_art',
    name: 'Mori Art Museum',
    category: 'museums',
    tags: ['museums', 'culture', 'photography'],
    rating: 4.4,
    reviewCount: 16000,
    cost: CostEstimate(
      low: 15,
      high: 15,
      currencyCode: 'USD',
      source: CostSource.userProvided,
    ),
    latitude: 35.6604,
    longitude: 139.7292,
    estimatedVisitMinutes: 120,
  ),
  TravelPlace(
    id: 'odaiba',
    name: 'Odaiba Seaside Park',
    category: 'nature',
    tags: ['nature', 'photography', 'attractions'],
    rating: 4.3,
    reviewCount: 15000,
    cost: CostEstimate.free(currencyCode: 'USD'),
    latitude: 35.6297,
    longitude: 139.7756,
    estimatedVisitMinutes: 120,
  ),
];
