// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDux0kLvwy5FC-YO75_t-8NLtH0bwuv5Vk',
    appId: '1:433112330933:web:c334aa622d3a34057144fc',
    messagingSenderId: '433112330933',
    projectId: 'travel-plan-5f810',
    authDomain: 'travel-plan-5f810.firebaseapp.com',
    storageBucket: 'travel-plan-5f810.firebasestorage.app',
    measurementId: 'G-P2ED9EF9GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5dbka3iqwqzDiLffm5am_tJzXJN_LF20',
    appId: '1:433112330933:android:e7698b84788e66167144fc',
    messagingSenderId: '433112330933',
    projectId: 'travel-plan-5f810',
    storageBucket: 'travel-plan-5f810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbs7AJMandOeSdPVfkKauFJtSSAw3H0fs',
    appId: '1:433112330933:ios:b82eb71c1d3a45a37144fc',
    messagingSenderId: '433112330933',
    projectId: 'travel-plan-5f810',
    storageBucket: 'travel-plan-5f810.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbs7AJMandOeSdPVfkKauFJtSSAw3H0fs',
    appId: '1:433112330933:ios:b82eb71c1d3a45a37144fc',
    messagingSenderId: '433112330933',
    projectId: 'travel-plan-5f810',
    storageBucket: 'travel-plan-5f810.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDux0kLvwy5FC-YO75_t-8NLtH0bwuv5Vk',
    appId: '1:433112330933:web:354af7da1eb8a3eb7144fc',
    messagingSenderId: '433112330933',
    projectId: 'travel-plan-5f810',
    authDomain: 'travel-plan-5f810.firebaseapp.com',
    storageBucket: 'travel-plan-5f810.firebasestorage.app',
    measurementId: 'G-WLJQ8WS6XL',
  );

}
